### ISSUE TITLE
New Matcher: isAnything()

### ISSUE THREAD

**Issue by oneronaut** [imbenjamin/brsHamcrest#11]
*Request:* Add an `isAnything()` matcher that will match anything. This won't have much use in direct matches. But when a matcher is used to define an expected parameter in a mocking framework, it becomes useful when you are defining params where you don't care what the value is. For example:
```
mock.given("fooFunction").with(["foo", isAnything(), true]).willReturn("bar")
```

**Comment by imbenjamin** [comment]
@oneronaut Just to confirm, is this just a dummy matcher that will always return `true`?

**Comment by oneronaut** [comment]
Yes. But it provides the Matcher interface so it still integrates with Rokito.
