### ISSUE TITLE
coreDoMatch does not ignore case differences in key names 

### ISSUE THREAD

**Issue by oneronaut** [imbenjamin/brsHamcrest#25]
**Issue:** Given the following statement:
```
obj = {fooKey : "fooValue"}
obj2 = parseJson{"{""fooKey"":""fooValue""}")
```
Then:
```
obj.items()[0].key = "fookey"
obj2.items()[0].key = "fooKey"
```
Note the difference in casing of the string representations of these keys.

So brsHamcrest's `coreDoMatch` needs to account for this when comparing key names.

**Comment by imbenjamin** [comment]
Closed by #26
